language: python
python:
  - "3.5"
  - "3.5-dev"  
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wkhtmltopdf xvfb
  - wkhtmltopdf --version
install:
  - pip install -r requirements.txt
  - sudo chmod +x setup-for-exec-no-x-server.sh
  - sudo ./setup-for-exec-no-x-server.sh
script:
  - python book-generator.py