language: python
python:
  - "3.7-dev"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wkhtmltopdf xvfb
  - wkhtmltopdf --version
install:
  - pip install -r requirements.txt
  - sudo chmod +x setup-for-exec-no-x-server.sh
  - sudo ./setup-for-exec-no-x-server.sh
script:
  - python book-generator.py
before_deploy:
      # See https://github.com/oliexdev/openScale/pull/121
      # Used to overwrite the GH release content because we use the GH Release feature
      # as a distribution channel for Draft regularly built by the CI
      - git config --local user.name "TravisCI"
      - git config --local user.email "build@travis-ci.com"
      - git tag -f CI_BUILD_RELEASE
      - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${github_personal_access_token}@github.com/${TRAVIS_REPO_SLUG}.git
      - git push -f gh CI_BUILD_RELEASE
      - git remote remove gh
deploy:
  provider: releases
  api_key: ${github_personal_access_token}
  name: CI_BUILD_RELEASE
  body: "Generation of the book from the CI job using the MASTER branch."
  draft: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  file: "owasp-cs-book.pdf"
  skip_cleanup: true
  on:
    branch: master