language: python
python:
  - "3.7-dev"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wkhtmltopdf xvfb
  - wkhtmltopdf --version
install:
  - pip install -r requirements.txt
  - sudo chmod +x setup-for-exec-no-x-server.sh
  - sudo ./setup-for-exec-no-x-server.sh
script:
  - python book-generator.py
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "TravisCI"
      - git config --local user.email "build@travis-ci.com"
      - git tag "CI_BUILD_RELEASE"
deploy:
  provider: releases
  name: DRAFT
  body: "Generation of the book from the CI job using the master branch."
  draft: true
  overwrite: true
  api_key: ${github_personal_access_token}
  file: "owasp-cs-book.pdf"
  skip_cleanup: true